"""
Multi-dataset hub layout under one parent root (e.g. /data1/wjh/HumanRetarget).

Each dataset is an isolated subdirectory with the **same** internal tree as a
standalone ``root_dir``. Pipeline stages always run with ``args.root_dir`` set
to ``<hub_root>/<dataset_name>``.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import List

from pipeline.dataset_schema import (
    DIR_PROCESSED,
    MANIFEST_DEFAULT,
    MAPPING_DEFAULT,
    SPLITS_DIR,
    STANDARD_DATASET_DIRS,
    layout_tree_text,
)

# Default mega-root; override via CLI ``--hub-root``.
DEFAULT_HUB_ROOT = "/data1/wjh/HumanRetarget"

HUB_META_FILENAME = "hub.json"


def resolve_dataset_root(hub_root: Path | str, dataset_name: str) -> Path:
    name = dataset_name.strip()
    if not name:
        raise ValueError("dataset name must be non-empty")
    if "/" in name or name in (".", ".."):
        raise ValueError(f"invalid dataset name: {name!r}")
    return Path(hub_root).expanduser().resolve() / name


def resolve_root_from_args(
    *,
    root_dir: str | None,
    hub_root: str | None,
    dataset: str | None,
) -> Path:
    if dataset and str(dataset).strip():
        hub = Path(hub_root or DEFAULT_HUB_ROOT).expanduser().resolve()
        return resolve_dataset_root(hub, str(dataset).strip())
    if not root_dir:
        raise ValueError("Provide --root_dir or (--hub-root and --dataset).")
    return Path(root_dir).expanduser().resolve()


def init_dataset_layout(dataset_root: Path, *, dataset_name: str, id_width: int = 6) -> Path:
    root = dataset_root.resolve()
    root.mkdir(parents=True, exist_ok=True)
    for sub in STANDARD_DATASET_DIRS:
        (root / sub).mkdir(parents=True, exist_ok=True)
    readme = root / SPLITS_DIR / "README.txt"
    if not readme.exists():
        readme.write_text(
            "Reserved for per-dataset train/val/test JSON. Not generated by default pipeline.\n",
            encoding="utf-8",
        )
    meta = {
        "dataset": dataset_name,
        "root_dir": str(root),
        "layout_version": 2,
        "manifest": MANIFEST_DEFAULT,
        "mapping": MAPPING_DEFAULT,
        "id_width": id_width,
        "train_sample_dir": f"{DIR_PROCESSED}/<sample_id>/",
    }
    (root / HUB_META_FILENAME).write_text(
        json.dumps(meta, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    return root


def is_dataset_root(path: Path) -> bool:
    p = path.resolve()
    if not p.is_dir():
        return False
    return (p / DIR_PROCESSED).is_dir() or (p / MANIFEST_DEFAULT).is_file()


def list_datasets(hub_root: Path | str) -> List[str]:
    hub = Path(hub_root).expanduser().resolve()
    if not hub.is_dir():
        return []
    names: List[str] = []
    for child in sorted(hub.iterdir()):
        if not child.is_dir() or child.name.startswith("."):
            continue
        if is_dataset_root(child):
            names.append(child.name)
    return names


def hub_layout_text(hub_root: str | Path = DEFAULT_HUB_ROOT) -> str:
    return layout_tree_text(str(Path(hub_root).expanduser()))
